import type { InboxItem } from "./types";

const now = "2026-08-24T14:00:00.000Z";

export const SEED_ITEMS: InboxItem[] = [
  {
    id: "seed-linda-001",
    createdAt: "2026-08-24T08:12:00.000Z",
    updatedAt: now,
    persona: "Linda Chambers",
    personaKey: "linda_chambers",
    caption:
      "Slow Sunday in the kitchen — rendered tallow on the stove and biscuits in the oven. This is the kind of skincare my grandmother would recognize.",
    comment: "",
    status: "pending",
    imageUrl: "https://picsum.photos/seed/linda-chambers-kitchen/720/960",
    mediaId: "pb_media_linda_001",
    postType: "lifestyle",
    weekdayName: "Mon",
    runDate: "2026-08-24",
    brand: "Montana Tallow",
  },
  {
    id: "seed-becca-001",
    createdAt: "2026-08-24T08:18:00.000Z",
    updatedAt: "2026-08-24T11:02:00.000Z",
    persona: "Becca Rose",
    personaKey: "becca_rose",
    caption:
      "Nashville humidity is no joke. This is my 31-year-old skin after a tallow balm and a walk down 12 South — no filter, just glow.",
    comment: "Tone down humidity line if ads team wants cleaner CTA.",
    status: "approved",
    imageUrl: "https://picsum.photos/seed/becca-rose-nashville/720/960",
    mediaId: "pb_media_becca_001",
    postType: "lifestyle",
    weekdayName: "Mon",
    runDate: "2026-08-24",
    brand: "Montana Tallow",
    reviewedByEmail: "reviewer@naturalabs.io",
    reviewedAt: "2026-08-24T11:02:00.000Z",
  },
  {
    id: "seed-brooke-001",
    createdAt: "2026-08-23T09:05:00.000Z",
    updatedAt: "2026-08-23T16:40:00.000Z",
    persona: "Brooke Swift",
    personaKey: "brooke_swift",
    caption:
      "Morning light in Annecy. I packed the tin in my tote and used it after the lake — simple, rich, and very French-girl without trying.",
    comment: "Please swap 'French-girl' — keep Brooke's voice, less cliché.",
    status: "changes_requested",
    imageUrl: "https://picsum.photos/seed/brooke-swift-annecy/720/960",
    mediaId: "pb_media_brooke_001",
    postType: "lifestyle",
    weekdayName: "Sun",
    runDate: "2026-08-23",
    brand: "Montana Tallow",
    reviewedByEmail: "reviewer@naturalabs.io",
    reviewedAt: "2026-08-23T16:40:00.000Z",
  },
  {
    id: "seed-claire-001",
    createdAt: "2026-08-24T08:22:00.000Z",
    updatedAt: now,
    persona: "Claire Donovan",
    personaKey: "claire_donovan",
    caption:
      "Austin Saturday: farmers market, iced tea, and the serum I actually finish. 42 and finally done chasing 12-step routines.",
    comment: "",
    status: "pending",
    imageUrl: "https://picsum.photos/seed/claire-donovan-austin/720/960",
    mediaId: "pb_media_claire_001",
    postType: "lifestyle",
    weekdayName: "Mon",
    runDate: "2026-08-24",
    brand: "Lumerval",
  },
  {
    id: "seed-linda-002",
    createdAt: "2026-08-17T10:00:00.000Z",
    updatedAt: "2026-08-17T15:12:00.000Z",
    persona: "Linda Chambers",
    personaKey: "linda_chambers",
    caption:
      "I do not need another miracle bottle. I need something I can scoop with my fingers after hanging laundry.",
    comment: "Image felt too product-shot. Deny and regenerate lifestyle frame.",
    status: "denied",
    imageUrl: "https://picsum.photos/seed/linda-chambers-porch/720/960",
    mediaId: "pb_media_linda_002",
    postType: "lifestyle",
    weekdayName: "Mon",
    runDate: "2026-08-17",
    brand: "Montana Tallow",
    reviewedByEmail: "reviewer@naturalabs.io",
    reviewedAt: "2026-08-17T15:12:00.000Z",
  },
  {
    id: "seed-becca-002",
    createdAt: "2026-08-24T08:30:00.000Z",
    updatedAt: now,
    persona: "Becca Rose",
    personaKey: "becca_rose",
    caption:
      "Kept the tin in my bag between studio and dinner. Tiny ritual, big payoff on dry air-conditioned skin.",
    comment: "",
    status: "pending",
    imageUrl: "https://picsum.photos/seed/becca-rose-studio/720/960",
    mediaId: "pb_media_becca_002",
    postType: "product",
    weekdayName: "Mon",
    runDate: "2026-08-24",
    brand: "Montana Tallow",
  },
  {
    id: "seed-brooke-002",
    createdAt: "2026-08-24T08:35:00.000Z",
    updatedAt: now,
    persona: "Brooke Swift",
    personaKey: "brooke_swift",
    caption:
      "After a swim I don't want a 10-step routine. I want one tin, clean hands, and the walk back through town.",
    comment: "",
    status: "pending",
    imageUrl: "https://picsum.photos/seed/brooke-swift-lake/720/960",
    mediaId: "pb_media_brooke_002",
    postType: "lifestyle",
    weekdayName: "Mon",
    runDate: "2026-08-24",
    brand: "Montana Tallow",
  },
  {
    id: "seed-claire-002",
    createdAt: "2026-08-18T12:10:00.000Z",
    updatedAt: "2026-08-18T18:00:00.000Z",
    persona: "Claire Donovan",
    personaKey: "claire_donovan",
    caption:
      "Office lighting is ruthless. This is my lunch-break reset — not a paid-ad bottle grid, just a woman in Austin who got tired of noise.",
    comment: "",
    status: "approved",
    imageUrl: "https://picsum.photos/seed/claire-donovan-office/720/960",
    mediaId: "pb_media_claire_002",
    postType: "lifestyle",
    weekdayName: "Tue",
    runDate: "2026-08-18",
    brand: "Lumerval",
    reviewedByEmail: "reviewer@naturalabs.io",
    reviewedAt: "2026-08-18T18:00:00.000Z",
  },
];
